language: node_js
node_js:
  - 12
install:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master