language: node_js
node_js:
  - "stable"
before_install:
  - npm install -g @lhci/cli@0.3.x
install:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm run build
  - lhci autorun
addons:
  chrome: stable

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
